### PR TITLE
Update for CodeMirror 5.20+

### PR DESCRIPTION
**Pull request by grahammiln**
- Fix build for v5.20.2.
- Minimal change to download from CodeMirror's secure constant link.

### CODE REVIEW

**Comment by swisspol** [comment]
What's wrong with downloading from GitHub which ensures you get a specific version?

**Comment by grahammiln** [comment]
As is, the script currently returns an error:

```
./Make_Bundle.sh 5.20.2

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   128    0   128    0     0    224      0 --:--:-- --:--:-- --:--:--   224
100   129    0   129    0     0    184      0 --:--:-- --:--:-- --:--:--   184
100  908k    0  908k    0     0   407k      0 --:--:--  0:00:02 --:--:--  820k

cp: CodeMirror/lib/codemirror.js: No such file or directory
```

This pull request fixes the error.

**Comment by swisspol** [comment]
Looks like the problem is that "releases" on GitHub don't contain the processed JS at `/lib/codemirror.js` anymore.

Downloading from http://codemirror.net/codemirror.zip works fine, but then the script would need to be changed to detect the version automatically instead of requiring it to be provided. Otherwise it doesn't make much sense.

**Comment by grahammiln** [comment]
I agree. Having the version number extracted from the download would be better.

For this pull request I tried to keep the change to the absolute minimum, just to restore functionality for now.

**Pull request merged**
